spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingengine
    username: bookingengine
    password: postgres
logging:
  level:
    root: INFO
    org:
      togglz: trace
application:
  uiHost: http://localhost:3000
  movieServiceHost: http://localhost:8000/
togglz:
  console:
    enabled: true
    path: /togglz-console
    secured: false
    use-management-port: false
